### ISSUE TITLE
Code lens run cell link not displayed in VSCode 1.19 (Windows 10)

### ISSUE THREAD

**Issue by msiers** [DonJayamanne/vscodeJupyter#94]
### Environment data
VS Code version: 1.19.0
Jupyter Extension version: 1.1.4
OS and version: Windows 10

### Actual behavior
Code lens "Run cell" link is not being displayed in text editor above the '#%%' line.

### Expected  behavior
Run cell link is displayed and can be used to execute the selected cell.

### Steps to reproduce:
- Create python source file with code lens cell line in it.
- Works in VSCode 1.18.1 but does not show up in VSCode 1.19.0.

**Comment by DonJayamanne** [comment]
Jupyter functionality has been deprecated in the Python extension, please install the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter)
All of the functionality related to Jupyter was pulled out of the Python extension into [this](https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter) separate  extension

**Comment by DonJayamanne** [comment]
* Please could you uninstall and re-install the extension.
* Do you have the latest version of the Python extension?
* Please could you provide the logs from the `console window` (Help -> Toggle Developer Tools)

**Comment by msiers** [comment]
I uninstalled and re-installed the Jupyter extension but this did not resolve the issue.
I have the Microsoft Python extension installed (version 0.9.0).

I am seeing the following error messages in the console window.


[Extension Host] Here is the error stack:  Error: Cannot find module 'untildify'
                at Function.Module._resolveFilename (module.js:470:15)
                at Function.Module._load (module.js:418:25)
                at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
                at Module.require (module.js:498:17)
                at require (internal/module.js:20:19)
                at Object.<anonymous> (C:\Users\msiers\.vscode\extensions\ms-python.python-0.9.0\out\client\common\configSettings.js:10:19)
                at Object.<anonymous> (C:\Users\msiers\.vscode\extensions\ms-python.python-0.9.0\out\client\common\configSettings.js:325:3)
                at Module._compile (module.js:571:32)
                at Object.Module._extensions..js (module.js:580:10)
                at Module.load (module.js:488:32)
                at tryModuleLoad (module.js:447:12)
                at Function.Module._load (module.js:439:3)
                at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
                at Module.require (module.js:498:17)
                at require (internal/module.js:20:19)
                at Object.<anonymous> (C:\Users\msiers\.vscode\extensions\ms-python.python-0.9.0\out\client\extension.js:16:18)
                at Object.<anonymous> (C:\Users\msiers\.vscode\extensions\ms-python.python-0.9.0\out\client\extension.js:192:3)
                at Module._compile (module.js:571:32)
                at Object.Module._extensions..js (module.js:580:10)
                at Module.load (module.js:488:32)
                at tryModuleLoad (module.js:447:12)
                at Function.Module._load (module.js:439:3)

**Comment by msiers** [comment]
Here is another message I am seeing in the console log.  This is reported for other
Jupyter extension functions as well.

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4054 [C:\Users\msiers\.vscode\extensions\ms-python.python-0.9.0]: Command `jupyter.execCurrentCell` appears multiple times in the `commands` section.

**Comment by DonJayamanne** [comment]
>[Extension Host] Here is the error stack:  Error: Cannot find module 'untildify'

This is the error. looks like the extension hasn't been installed correctly. 
Please uninstall both extensions, reload vs code.
Install the Python extension first, then the jupyter extension.

**Comment by msiers** [comment]
Thanks.  Uninstalling and reinstalling both extensions resolved the issue.
